import React, { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  'English (US)': {
    dashboard: 'Dashboard',
    notes: 'Notes',
    quiz: 'Quiz',
    flashcards: 'Flashcards',
    pomodoro: 'Pomodoro',
    goals: 'Goals',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    home: 'Home',
    'ai assistant': 'AI Assistant',
    active_courses: 'Active Courses',
    focus_time: 'Focus Time',
    study_streak: 'Study Streak',
    ai_tokens: 'AI Tokens',
    recent_activity: 'Recent Activity',
    weekly_progress: 'Weekly Progress',
    my_goals: 'My Goals',
    add_goal: 'Add Goal',
    my_notes: 'My Notes',
    new_note: 'New Note',
    search_notes: 'Search notes...',
    quiz_generator: 'Quiz Generator',
    recent_quizzes: 'Recent Quizzes',
    generate_now: 'Generate Now',
    my_profile: 'My Profile',
    edit_profile: 'Edit Profile',
    app_settings: 'App Settings',
    appearance: 'Appearance',
    notifications: 'Notifications',
    welcome_back: 'Welcome back',
    ready_to_crush: "Ready to crush your goals today?",
    start_session: 'Start Study Session',
    weekly_focus: 'Weekly Focus',
    todays_deadlines: "Today's Deadlines",
    ai_insight: 'AI Insight',
    leaderboard: 'Leaderboard',
    study_plan: 'Create Study Plan',
    // Notes Module
    all_notes: 'All Notes',
    search_placeholder: 'Search in your notes...',
    no_notes: 'No notes yet.',
    create_first_note: 'Create your first note today!',
    note_details: 'Note Details',
    save_note: 'Save Note',
    delete_note: 'Delete Note',
    // Quiz Module
    take_quiz: 'Take Quiz',
    quiz_results: 'Quiz Results',
    start_quiz: 'Start Quiz',
    score: 'Score',
    questions: 'Questions',
    correct: 'Correct',
    wrong: 'Wrong',
    generate_quiz: 'Generate Quiz',
    topic: 'Topic',
    // Flashcards Module
    study_flashcards: 'Study Flashcards',
    flip_card: 'Flip card',
    next_card: 'Next card',
    previous_card: 'Previous card',
    mastered: 'Mastered',
    review: 'Needs review',
    // Profile Module
    full_name: 'Full Name',
    school_university: 'School / University',
    save_changes: 'Save Changes',
    badges: 'Badges',
    study_xp: 'Study XP',
    notes_created: 'Notes Created',
    quizzes_completed: 'Quizzes Completed',
    // General
    cancel: 'Cancel',
    loading: 'Loading...',
    success: 'Success!',
    error: 'Error!',
    coming_soon: 'Coming Soon!',
    // AI Assistant
    ai_companion: 'AI Study Companion',
    ai_status: 'Online & Ready to Help',
    ai_placeholder: 'Ask anything about your studies...',
    // Pomodoro
    focus_timer: 'Focus Timer',
    pomodoro_desc: 'Science-backed focus sessions. Stay sharp, stay efficient.',
    focus: 'Focus',
    break: 'Break',
    long_break: 'Long Break',
    // Goals
    study_goals: 'Study Goals',
    goals_desc: 'Track your milestones and achieve academic excellence.',
    set_goal: 'Set New Goal',
    missions_completed: 'Missions Accomplished',
    insights: 'Insights',
    productivity_tip: 'Productivity Tip',
    // Quiz
    quiz_desc: 'Test your knowledge with AI-powered quizzes',
    ai_magic: 'AI Magic Generator',
    ai_magic_desc: "Enter a topic or paste your notes, and I'll generate a personalized quiz to test your mastery.",
    attach_notes: 'Attach notes or text file...',
    accuracy: 'Accuracy',
    // Notifications
    notifications_title: 'Notifications',
    notifications_desc: 'Stay updated with your study progress',
    mark_all_read: 'Mark all read',
    no_notifications: "That's all for now!",
    caught_up: "You're all caught up with your notifications.",
    // Goals
    no_goals: 'No goals set yet',
    first_goal_desc: 'Every great achievement starts with a single goal. What will you conquer today?',
    first_goal_btn: 'Create your first goal',
    mastermind: 'Mastermind!',
    on_fire: 'On Fire!',
    keep_pushing: 'Keep Pushing!',
    conquered_missions: "You've conquered {{rate}}% of your missions so far.",
    // Landing Page
    hero_title_1: 'Study',
    hero_title_2: 'Smarter',
    hero_title_3: 'Not Harder.',
    hero_subtitle: 'The all-in-one AI-powered study companion designed for modern students. Generate quizzes, summarize notes, and crush your exams with ease.',
    join_students: 'Join 10k+ Students',
    watch_demo: 'Watch Demo',
    features_title: 'Unleash Your Potential',
    features_subtitle: 'Everything you need to master any subject in record time.',
    ai_assistant_title: 'AI Study Assistant',
    ai_assistant_desc: 'Get instant answers and step-by-step explanations for complex problems.',
    smart_quizzes_title: 'Smart Quizzes',
    smart_quizzes_desc: 'Convert any text or PDF into interactive quizzes to test your knowledge.',
    focus_tracking_title: 'Focus Tracking',
    focus_tracking_desc: 'Built-in Pomodoro and goal tracking to keep you motivated and productive.',
    how_it_works: 'How it works',
    pricing: 'Pricing',
    features: 'Features',
    login: 'Login',
    get_started: 'Get Started'
  },
  'Español': {
    dashboard: 'Tablero',
    notes: 'Notas',
    quiz: 'Prueba',
    flashcards: 'Tarjetas',
    pomodoro: 'Pomodoro',
    goals: 'Metas',
    profile: 'Perfil',
    settings: 'Ajustes',
    logout: 'Cerrar sesión',
    home: 'Inicio'
  },
  'Français': {
    dashboard: 'Tableau',
    notes: 'Notes',
    quiz: 'Quiz',
    flashcards: 'Cartes',
    pomodoro: 'Pomodoro',
    goals: 'Objectifs',
    profile: 'Profil',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    home: 'Accueil'
  },
  'Deutsch': {
    dashboard: 'Dashboard',
    notes: 'Notizen',
    quiz: 'Quiz',
    flashcards: 'Lernkarten',
    pomodoro: 'Pomodoro',
    goals: 'Ziele',
    profile: 'Profil',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    home: 'Start'
  },
  'Filipino': {
    dashboard: 'Talahanayan',
    notes: 'Mga Tala',
    quiz: 'Pagsusulit',
    flashcards: 'Tarhetas',
    pomodoro: 'Pomodoro',
    goals: 'Mga Layunin',
    profile: 'Profile',
    settings: 'Mga Setting',
    logout: 'Mag-logout',
    home: 'Simula',
    'ai assistant': 'Katuwang na AI',
    active_courses: 'Aktibong mga Kurso',
    focus_time: 'Oras ng Pag-aaral',
    study_streak: 'Sunod-sunod na Pag-aaral',
    ai_tokens: 'AI Tokens',
    recent_activity: 'Kamakailang Gawain',
    weekly_progress: 'Lingguhang Pag-unlad',
    my_goals: 'Aking mga Layunin',
    add_goal: 'Magdagdag ng Layunin',
    my_notes: 'Aking mga Tala',
    new_note: 'Bagong Tala',
    search_notes: 'Maghanap ng tala...',
    quiz_generator: 'Tagagawa ng Pagsusulit',
    recent_quizzes: 'Kamakailang Pagsusulit',
    generate_now: 'Gumawa Ngayon',
    my_profile: 'Aking Profile',
    edit_profile: 'I-edit ang Profile',
    app_settings: 'Mga Setting ng App',
    appearance: 'Itsura',
    notifications: 'Mga Abiso',
    welcome_back: 'Maligayang pagbabalik',
    ready_to_crush: 'Handa ka na bang tapusin ang iyong mga layunin ngayong araw?',
    start_session: 'Magsimula ng Pag-aaral',
    weekly_focus: 'Lingguhang Pokus',
    todays_deadlines: 'Mga Deadline Ngayon',
    ai_insight: 'AI Insight',
    leaderboard: 'Talaan ng Nangunguna',
    study_plan: 'Gumawa ng Study Plan',
    // Notes Module
    all_notes: 'Lahat ng mga Tala',
    search_placeholder: 'Maghanap sa iyong mga tala...',
    no_notes: 'Wala pang mga tala.',
    create_first_note: 'Gawing ang iyong unang tala ngayon!',
    note_details: 'Detalye ng Tala',
    save_note: 'I-save ang Tala',
    delete_note: 'I-delete ang Tala',
    // Quiz Module
    take_quiz: 'Kumuha ng Pagsusulit',
    quiz_results: 'Resulta ng Pagsusulit',
    start_quiz: 'Simulan ang Pagsusulit',
    score: 'Iskor',
    questions: 'Mga Tanong',
    correct: 'Tama',
    wrong: 'Mali',
    generate_quiz: 'Gumawa ng Pagsusulit',
    topic: 'Paksa',
    // Flashcards Module
    study_flashcards: 'Mag-aral gamit ang Flashcards',
    flip_card: 'I-flip ang card',
    next_card: 'Susunod na card',
    previous_card: 'Nakaraang card',
    mastered: 'Mastered na',
    review: 'Kailangan pang i-review',
    // Profile Module
    full_name: 'Buong Pangalan',
    school_university: 'Paaralan / Unibersidad',
    save_changes: 'I-save ang mga Pagbabago',
    badges: 'Mga Badge',
    study_xp: 'Study XP',
    notes_created: 'Mga Talang Ginawa',
    quizzes_completed: 'Pagsusulit na Natapos',
    // General
    cancel: 'I-cancel',
    loading: 'Naglo-load...',
    success: 'Tagumpay!',
    error: 'Error!',
    coming_soon: 'Malapit na!',
    // AI Assistant
    ai_companion: 'Katuwang na AI sa Pag-aaral',
    ai_status: 'Online at Handa Tumulong',
    ai_placeholder: 'Magtanong tungkol sa iyong pag-aaral...',
    // Pomodoro
    focus_timer: 'Timer ng Pokus',
    pomodoro_desc: 'Science-backed focus sessions. Manatiling matalas, manatiling mahusay.',
    focus: 'Pokus',
    break: 'Pahinga',
    long_break: 'Mahabang Pahinga',
    // Goals
    study_goals: 'Mga Layunin sa Pag-aaral',
    goals_desc: 'Subaybayan ang iyong mga milestone at makamit ang akademikong kahusayan.',
    set_goal: 'Magtakda ng Layunin',
    missions_completed: 'Mga Misyong Natapos',
    insights: 'Mga Insight',
    productivity_tip: 'Tip sa Produktibidad',
    // Notifications
    notifications_title: 'Mga Abiso',
    notifications_desc: 'Manatiling updated sa iyong pag-unlad sa pag-aaral',
    mark_all_read: 'I-marka lahat bilang nabasa na',
    no_notifications: 'Iyon na ang lahat sa ngayon!',
    caught_up: 'Lahat ay nabasa na sa iyong mga abiso.',
    // Goals
    no_goals: 'Wala pang nakatakdang layunin',
    first_goal_desc: 'Bawat malaking tagumpay ay nagsisimula sa isang layunin. Ano ang iyong gagawin ngayon?',
    first_goal_btn: 'Gawin ang iyong unang layunin',
    mastermind: 'Mastermind!',
    on_fire: 'Nagbabaga!',
    keep_pushing: 'Ipagpatuloy lang!',
    conquered_missions: "Natapos mo na ang {{rate}}% ng iyong mga misyon.",
    // Landing Page
    hero_title_1: 'Mag-aral nang',
    hero_title_2: 'Matalino',
    hero_title_3: 'Hindi nang Mahirap.',
    hero_subtitle: 'Ang all-in-one na AI study companion para sa modernong mag-aaral. Gumawa ng pagsusulit, ibuod ang mga tala, at ipasa ang iyong mga exam nang madali.',
    join_students: 'Sumali sa 10k+ Mag-aaral',
    watch_demo: 'Panoorin ang Demo',
    features_title: 'Ilabas ang Iyong Potensyal',
    features_subtitle: 'Lahat ng kailangan mo para ma-master ang anumang paksa sa mabilis na panahon.',
    ai_assistant_title: 'AI Study Assistant',
    ai_assistant_desc: 'Kumuha ng agarang sagot at sunod-sunod na paliwanag para sa mga kumplikadong problema.',
    smart_quizzes_title: 'Smart Quizzes',
    smart_quizzes_desc: 'Gawing interactive na pagsusulit ang anumang text o PDF para subukin ang iyong kaalaman.',
    focus_tracking_title: 'Focus Tracking',
    focus_tracking_desc: 'Built-in na Pomodoro at goal tracking para mapanatili ang iyong motibasyon.',
    how_it_works: 'Paano ito gumagana',
    pricing: 'Presyo',
    features: 'Mga Tampok',
    login: 'Mag-login',
    get_started: 'Simulan na'
  },
  '日本語': {
    dashboard: 'ダッシュボード',
    notes: 'ノート',
    quiz: 'クイズ',
    flashcards: '単語帳',
    pomodoro: 'ポモドーロ',
    goals: '目標',
    profile: 'プロフィール',
    settings: '設定',
    logout: 'ログアウト',
    home: 'ホーム'
  },
  '中文': {
    dashboard: '仪表板',
    notes: '笔记',
    quiz: '测试',
    flashcards: '抽认卡',
    pomodoro: '番茄钟',
    goals: '目标',
    profile: '个人资料',
    settings: '设置',
    logout: '登出',
    home: '首页'
  }
}

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('appLanguage') || 'English (US)')

  useEffect(() => {
    localStorage.setItem('appLanguage', language)
  }, [language])

  const t = (key) => {
    return translations[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider')
  return context
}
